# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: OWASP
        uses: DependencyTrack/gh-upload-sbom@v2.0.0
        with:
          serverhostname: 'dt.cto.aks.egdev.eu'
          apikey: '${{ secrets.SECRET_OWASP_DT_KEY }}'
          project: 'e06b988c-2100-4e95-b6eb-5d07792b6f42'
          bomfilename: '/home/runner/work/github_demo/github_demo/target/bom.xml'
      - run: ls -R
