name: Zephyr Scale integration test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  ZephyrTest:
    runs-on: [self-hosted, k8s]
    name: Zephyr Scale integration test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Zephyr
        id: Zephyr
        uses: EG-A-S/cto-actions-zephyr@main
        with:
            tests_kind: 'Cucumber'
            tests_path: src/test/java/com/example/javamavenjunithelloworld
            jira_project: 'DEM'       
            auto_test_creation: 'False' 
            api_token: ${{secrets.JIRA_TOKEN}}
