name: Zephyr Scale

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  zephyrscale:
    runs-on: ubuntu-latest
    name: Zephyr Scale integration test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Zephyr
        uses: EG-A-S/cto-actions-zephyr@main
        with:
            tests_kind: 'JUnit'
            tests_path: './src/test/java/com/example/javamavenjunithelloworld/'
            jira_project: 'DEM'      
            auto_test_creation: 'True'
            api_token: ${{secrets.JIRA_TOKEN}}